### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ValuesFeng** [lrannn/SimpleRecorder#1]
建议给Recorder改成Builder模式，有些参数可以给成默认的。
构造的方式真的太啰嗦麻烦了，一般超过3个参数的构造方法就狠烦人了。

**Comment by mocchi123** [comment]
will try

**Comment by lrannn** [comment]
Builder模式我也想过，但是怕使用的时候忘传一些参数，所以才在构造方法设置QAQ
